# This is a basic workflow to help you get started with Actions

name: element-vue Docker Image CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # package vue
    - name: npm install, build
      run: |
        npm ci
        npm run build --if-present
      env:
        CI: true
    
    # package docker image
    - name: Login docker registry
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag leyius/element-vue:latest
    - name: Push docker image
      run: docker push leyius/element-vue:latest
    - name: remove docker image
      run: docker rmi leyius/element-vue:latest
